### ISSUE TITLE
App does not work during debug

### ISSUE THREAD

**Issue by jtv7** [prey/prey-ios-client#57]
Various app features do not work when deploying from Xcode or Ad-Hoc, such as location or alert notifications.  Why is this and how do I fix it?  Thanks!

**Comment by jCalaU** [comment]
Hi jtv7,

Prey uses APNS (Apple Push Notification Service) to communicate with the app on iOS.  Prey server uses a specific certificate to send push notifications, when you install the app via Xcode o Ad-Hoc you use a different certificate for this reason the Prey panel can't connect with the app because they have different certificates.  You would need your own server to send push notifications.

Feel free to open up a new one if you have other issues.
